// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiuwzOKwClicfbsu__kZnl5qQkyjrvePE',
    appId: '1:350470427377:web:1f5c6c7a6b617865d14f50',
    messagingSenderId: '350470427377',
    projectId: 'foodmanager-f117f',
    authDomain: 'foodmanager-f117f.firebaseapp.com',
    storageBucket: 'foodmanager-f117f.firebasestorage.app',
    measurementId: 'G-WDH59XFXHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoRWeMuV6TSV8LO211UzIZvDFAmD6Z4Y',
    appId: '1:350470427377:android:51b6b370da1049dad14f50',
    messagingSenderId: '350470427377',
    projectId: 'foodmanager-f117f',
    storageBucket: 'foodmanager-f117f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr6NLD7XUJhXobPs5mQRSLtNrCHzaitEQ',
    appId: '1:350470427377:ios:424cf6c8c3e20792d14f50',
    messagingSenderId: '350470427377',
    projectId: 'foodmanager-f117f',
    storageBucket: 'foodmanager-f117f.firebasestorage.app',
    iosBundleId: 'com.example.foodManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr6NLD7XUJhXobPs5mQRSLtNrCHzaitEQ',
    appId: '1:350470427377:ios:424cf6c8c3e20792d14f50',
    messagingSenderId: '350470427377',
    projectId: 'foodmanager-f117f',
    storageBucket: 'foodmanager-f117f.firebasestorage.app',
    iosBundleId: 'com.example.foodManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiuwzOKwClicfbsu__kZnl5qQkyjrvePE',
    appId: '1:350470427377:web:8c94f7f558c1d10ed14f50',
    messagingSenderId: '350470427377',
    projectId: 'foodmanager-f117f',
    authDomain: 'foodmanager-f117f.firebaseapp.com',
    storageBucket: 'foodmanager-f117f.firebasestorage.app',
    measurementId: 'G-QLWDNETEPJ',
  );
}
