@startuml 
title Sequence Diagram for View and Create Smart List 

actor User
participant "Flutter App" as App
participant "Firebase Database" as DB

User -> App : View Smart List For Current Meal Plan
App -> DB : Retrieve existing list data
DB --> App : Return list data
App -> User : Display Smart List

alt No Smart List for current meal plan
  User -> App : Create List
  App -> DB : Fetch Meal Plan Ingredients
  DB -> App : Return Meal Plan Ingredients
  App -> DB : Save new list
  DB --> App : Confirmation
end

alt User changes the store
  User -> App : Change Store
  App -> DB : Fetch updated minimum pack size data
  DB --> App : Return minimum pack sizes data
  App -> DB : Save updated data
  DB --> App : Confirmation
end

App -> DB : Fetch required data for calculations
DB --> App : Return data

App -> User : Display updated Smart List

@enduml
